### ISSUE TITLE
Is OPTM really faster? 

### ISSUE THREAD

**Issue by mpariente** [lawlict/EEND_loss#1]
Thanks a lot for the implementation, it's great to have to have all three possibilities in the same code-base to be able to benchmark those. 

We have something similar in Asteroid, (`PITLossWrapper`)[https://github.com/mpariente/asteroid/blob/master/asteroid/losses/pit_wrapper.py#L8], which can convert any loss function into a PIT loss function. 
I've had a look at the Hungarian algorithm in the past and thought about integrating it but I thought the time spent on CPU-GPU transfers would outweigh the gain of the Hungarian algorithm. 

I cannot access your paper so I don't see if you made the experiments, but I guess yes. Did you actually gain some time or lose some time when using `OPTMLoss` against `FastPITLoss`? 

Thanks, 
Manu

**Comment by hbredin** [comment]
Salut Manu. Paper is here: https://www.isca-speech.org/archive/Odyssey_2020/pdfs/17.pdf

**Comment by mpariente** [comment]
Thanks and sorry, only found the abstract earlier. 
Well, this answers my question. I guess I'll have to use it then
